#!/usr/bin/env ruby

require 'serialport'

case ENV["IAM"]
when "mac"
  whoiam = ENV["IAM"]
  port_str = "/dev/tty.usbserial-AB0N63JR"
when "raspi"
  whoiam = ENV["IAM"]
  port_str = "/dev/serial0"
else
  raise "unknown iam"
end
baud_rate = 9600
data_bits = 8
stop_bits = 1
parity = 0

sp = SerialPort.new(port_str, baud_rate, data_bits, stop_bits, parity)

puts "start..."
# sp.write_nonblock "1234gfjdknf\n"
sp.write "a"

puts "end..."
sp.close
